function ViewMobileNumber(redUrl,event_url){var url=redUrl+"&sid="+Math.random();$.ajax({type:'POST',url:url,dataType:"html",data:{action_id:"action_view_mobile_number",ref_url:event_url},cache:!1,success:function(newHTML){$('#post_req_popup_ei').html(newHTML);$('#overlay_s').css({'display':'block','position':'fixed'});$("#user_name").trigger('blur');login_status_and_mobile_verify_status(url,event_url)},xhrFields:{withCredentials:!0},crossDomain:!0})}
function login_status_and_mobile_verify_status(url,event_url){$.ajax({type:'POST',url:url,dataType:"json",data:{action_id:"login_status_and_mobile_verify_status",ref_url:event_url},cache:!1,success:function(obj){if(obj.login_status=='Y'&&obj.mobile_verify_status=='N'){var your_name=$("#form_id_view_mob").find('#your_name');if(obj.isd_code<1){obj.isd_code='91'}
if(obj.country==''){obj.country='in'}
$("#form_id_view_mob").find("#your_name").val(obj.your_name);$("#form_id_view_mob").find("#username").val(obj.username);$("#form_id_view_mob").find("#isd_code2").val(obj.isd_code);$("#form_id_view_mob").find("#MobInput").val(obj.mobile);$("#form_id_view_mob").find('span[id^="MobText"]').html('+'+obj.mobile);$("#form_id_view_mob").find('span[id^="MobText_3"]').html(obj.mobile);$("#form_id_view_mob").find("#verify_mobile_country_id").val(obj.country);$("#form_id_view_mob").find("#username").prop('readonly',!0);$("#form_id_view_mob").find("#btn_submit").click()}},xhrFields:{withCredentials:!0},crossDomain:!0})}
function popupRefund(member_id,lead_id,subject,purchased_date,purchase_days){var mem_b_url=$("#mem_baseurl").val();var url=mem_b_url+'/lead_refund.php?member_id='+member_id+'&lead_id='+lead_id+'&subject='+subject+'&purchased_date='+purchased_date+'&purchase_days='+purchase_days;$.ajax({type:'POST',url:url,cache:!1,success:function(newHTML){$.fancybox({'content':newHTML,'maxWidth':600,'maxHeight':330,'fitToView':!1,'width':'95%','height':'95%','autoSize':!1,'closeClick':!1,'openEffect':'none','type':'ajax',})},xhrFields:{withCredentials:!0},error:function(xhr,status){if(xhr.status==404){alert('Page Not Found.')}else if(xhr.status==401){alert('Authorization Required.')}}})}
function PopupBannerAdvertis(url){$.ajax({type:'POST',url:url,dataType:"html",cache:!1,success:function(newHTML){$('#post_req_popup_ei').html(newHTML)},xhrFields:{withCredentials:!0},error:function(xhr,status){if(xhr.status==404){alert('Page Not Found.')}else if(xhr.status==401){alert('Authorization Required.')}}})}
function throttle(fn,timeout){var tid=0;return function(){clearTimeout(tid);var args=[].slice.call(arguments),ctx=this;tid=setTimeout(function(){fn.apply(ctx,args)},timeout)}}
var old_scroll_top=0;$(window).on('scroll',throttle(function(){var popH=$('#popupContact_s').height()+80;var dgH=$(window).height();var current_scroll_top=$(this).scrollTop();var scroll_delta=current_scroll_top-old_scroll_top;if(dgH<=popH){if(navigator.userAgent.indexOf("Firefox")>0){if(old_scroll_top<=current_scroll_top){$('.popup_box').css({'position':'absolute','top':old_scroll_top+(scroll_delta/2)})}else if(old_scroll_top>=current_scroll_top){$('.popup_box').css({'position':'absolute','top':current_scroll_top})}}else{if(old_scroll_top<=current_scroll_top){$('.popup_box').css({'position':'absolute','top':old_scroll_top})}else if(old_scroll_top>=current_scroll_top){$('.popup_box').css({'position':'absolute','top':current_scroll_top})}}}else($('.popup_box').css({'position':'','top':''}));old_scroll_top=current_scroll_top},100))
function return_member_pop_url(page_name){var action_url="";if(document.domain=='192.168.1.104'){action_url="//192.168.1.104/members/"+page_name}else if(document.domain.indexOf('betaei.in')>0){action_url="//members.betaei.in/"+page_name}else{action_url="//members.exportersindia.com/"+page_name}
return action_url}
if(document.domain=='192.168.1.104'){if(document.getElementById("mobile_script_ei")){$('<link rel="stylesheet" type="text/css" href="/static/css/root-css/mobile_popup_ei.css" >').appendTo("head")}else{$('<link rel="stylesheet" type="text/css" href="/static/css/root-css/popup_ei.css" >').appendTo("head")}}else if(document.domain.indexOf('betaei.in')>0){if(document.getElementById("mobile_script_ei")){$('<link rel="stylesheet" type="text/css" href="//www.betaei.in/static/css/root-css/mobile_popup_ei.css" >').appendTo("head")}else{$('<link rel="stylesheet" type="text/css" href="//www.betaei.in/static/css/root-css/popup_ei.css" >').appendTo("head")}}else{if(document.getElementById("mobile_script_ei")){$('<link rel="stylesheet" type="text/css" href="//static.exportersindia.com/css/root-css/mobile_popup_ei.css" >').appendTo("head")}else{$('<link rel="stylesheet" type="text/css" href="//static.exportersindia.com/css/root-css/popup_ei.css" >').appendTo("head")}}
function closeMe(){var pageName=window.location.pathname;if(pageName=='/guest-to-free-thanks.php'||pageName=='/thanks.htm'||pageName=='/members/thanks.htm'||pageName=='/join-now.php'||pageName=='/members/join-now.php'||pageName=='/members/guest-member-join-now.php'||pageName=='/guest-member-join-now.php'||pageName=='/members/index.php'||pageName=='/index.php'||pageName=='/members/add_edit_product.php'||pageName=='/add_edit_product.php'||pageName=='/members/add_product.php'||pageName=='/join-now-thanks.php'||pageName=='/members/verify-your-communication-details.php'||pageName=='/verify-your-communication-details.php'||pageName=='/members/purchased-lead.php'||pageName=='/signin.htm'||pageName=='/members/search-lead.php'||pageName=='/members/buy-lead.php'){$('#popup_ei').html('');if(pageName=='/signin.htm'){$('#login_popup_container').html('')}}else{parent.location.reload(!0)}}
function closeMyReqForm(){if(document.domain=='192.168.1.104'){var ajax_url='//192.168.1.104'}else if(document.domain.indexOf('betaei.in')>0){var ajax_url='//www.betaei.in/'}else{var ajax_url='//www.exportersindia.com'}
var reload_page='N'
if($('#reload_page').length>0){reload_page=$('#reload_page').val()}
if($('#second_step_post_r_form').length>0||reload_page=='Y'){$('#post_req_popup_ei').html('');$('#mobile_script_ei').html('')}else{$('#post_req_popup_ei').html('');$('#mobile_script_ei').html('')}
if($("#post-requirement-form")[0]){$("#post-requirement-form")[0].reset()}}
function closeMeViewMobile(){$('#post_req_popup_ei').html('')}
$(window).on('keyup',function(e){var inq_val="";if($('#inq_source').length){inq_val=$('#inq_source').val()}
if(inq_val!='auto_popup_postrequirment_send_inquiry'){var key=e.keyCode;if(key==27){$('#popup_ei').html('');$('#post_req_popup_ei').html('')}}})
function verify_popup_open(frmid,redUrl,flag){var redirct=redUrl||'';var tFlag=flag||'';xmlHttp=GetXmlHttpObject();if(xmlHttp==null){alert("Browser does not support HTTP Request");return}
var action_url=return_member_pop_url('');if(frmid=='signin'){var url=action_url+"verification_popup_form.php?frmid=signin&sid="+Math.random()}else if(frmid=='forget_pass'){var url=action_url+"verification_popup_form.php?frmid=forget_pass&sid="+Math.random()}else if(frmid=='mobile_verify'){var mobile_phone=document.getElementById("mobile_phone").value;var mobile_phone_country=document.getElementById("country").value;var country_arr=mobile_phone_country.split("^");var url=action_url+"verification_popup_form.php?frmid=mobile_verify&mobile_phone="+mobile_phone+"&country="+country_arr[0]+"&sid="+Math.random()}
xmlHttp.onreadystatechange=function ver_form(){if(xmlHttp.readyState==4){if(xmlHttp.responseText.length>0){var newHTML=xmlHttp.responseText;$('#popup_ei').html(newHTML);$('#overlay_s').css({'display':'block','position':'fixed'})}}};xmlHttp.open("GET",url,!0);xmlHttp.send(null)}
function signIn(redUrl,flag){var redirct=redUrl||'';var tFlag=flag||'';xmlHttp=GetXmlHttpObject();if(xmlHttp==null){alert("Browser does not support HTTP Request");return}
var mob_phone=document.getElementById('mobile_phone').value;var action_url=return_member_pop_url('');var url=action_url+"verification_popup_form.php?frmid=signin&mobile_phone="+mob_phone+"&sid="+Math.random();xmlHttp.onreadystatechange=function ver_form(){if(xmlHttp.readyState==4){if(xmlHttp.responseText.length>0){var newHTML=xmlHttp.responseText;$('#popup_ei').html(newHTML);$('#overlay_s').css({'display':'block','position':'fixed'})}}};xmlHttp.open("GET",url,!0);xmlHttp.send(null)}
function forgot_pass(redUrl,flag){var emailid='';var redirct=redUrl||'';var tFlag=flag||'';var mob_phone=document.getElementById('mobile_phone').value;xmlHttp=GetXmlHttpObject();if(xmlHttp==null){alert("Browser does not support HTTP Request");return}
var action_url=return_member_pop_url('');var url=action_url+"verification_popup_form.php?frmid=forget_pass&mobile_phone="+mob_phone+"&sid="+Math.random();xmlHttp.onreadystatechange=function ver_form(){if(xmlHttp.readyState==4){if(xmlHttp.responseText.length>0){var newHTML=xmlHttp.responseText;$('#popup_ei').html(newHTML);$('#overlay_s').css({'display':'block','position':'fixed'})}}};xmlHttp.open("GET",url,!0);xmlHttp.send(null)}
function mobileVerify(redUrl,flag,editstatus){var redirct=redUrl||'';var tFlag=flag||'';var emailid='';xmlHttp=GetXmlHttpObject();if(xmlHttp==null){alert("Browser does not support HTTP Request");return}
var mobile_phone=document.getElementById("mobile_phone").value;var mobile_phone_country=document.getElementById("country").value;var mobile_script_ei='N';if(document.getElementById("mobile_script_ei")){mobile_script_ei='Y';var send_country_code=mobile_phone_country}else{var country_arr=mobile_phone_country.split("^");var send_country_code=country_arr[0]}
var action_url=return_member_pop_url('');var url=action_url+"verification_popup_form.php?frmid=mobile_verify&mobile_phone="+mobile_phone+"&country="+send_country_code+"&mob_script="+mobile_script_ei+"&sid="+Math.random();xmlHttp.onreadystatechange=function ver_form(){if(xmlHttp.readyState==4){if(xmlHttp.responseText.length>0){var newHTML=xmlHttp.responseText;$('#popup_ei').html(newHTML);$('#overlay_s').css({'display':'block','position':'fixed'});if(editstatus=='Y'){$("#edit_mobile").show('fast');$("#veriry_code3").show('fast');$("#save_mobile").hide('fast');$("#verfications").hide('fast');$("#veriry_code1").hide('fast');$("#veriry_code2").hide('fast')}}}};xmlHttp.open("GET",url,!0);xmlHttp.send(null)}
function mobileVerifyLoginMember(redUrl,flag,editstatus,mobile_number,country){var redirct=redUrl||'';var tFlag=flag||'';var emailid='';var page_id='';if(document.getElementById("verify_popop_page_id")){page_id=document.getElementById("verify_popop_page_id").value}
var mobile_phone=mobile_number;var mobile_phone_country=country;var country_arr=mobile_phone_country.split("^");var action_url=return_member_pop_url('');var mobile_script_ei='N';if(document.getElementById("mobile_script_ei")){mobile_script_ei='Y'}
var url=action_url+"verification_popup_form.php?frmid=mobile_verify&add_edit_mobile="+editstatus+"&popop_page_id="+page_id+"&mobile_phone="+mobile_phone+"&country="+country_arr[0]+"&mob_script="+mobile_script_ei;$(document).ready(function(){$.ajax({type:'POST',url:url,dataType:"html",data:{action_id:"mobile_verify"},cache:!1,success:function(newHTML){$('#popup_ei').html(newHTML);$('#overlay_s').css({'display':'block','position':'fixed'});if(editstatus=='Y'){$("#edit_mobile").show('fast');$("#send_code").hide('fast');$("#enter_code").hide('fast');$("#thanks").hide('fast');$("#missed_call").hide('fast')}},xhrFields:{withCredentials:!0}})})}
function mobileVerifyTradeLeadLoginMember(redUrl,flag,editstatus,mobile_number,country){var redirct=redUrl||'';var tFlag=flag||'';var emailid='';var page_id='';if(document.getElementById("verify_popop_page_id")){page_id=document.getElementById("verify_popop_page_id").value}
var mobile_phone=mobile_number;var mobile_phone_country=country;var country_arr=mobile_phone_country.split("^");var action_url=return_member_pop_url('');var mobile_script_ei='N';if(document.getElementById("mobile_script_ei")){mobile_script_ei='Y'}
var url=action_url+"verification_popup_form.php?frmid=mobile_verify&add_edit_mobile="+editstatus+"&popop_page_id="+page_id+"&mobile_phone="+mobile_phone+"&country="+country_arr[0]+"&mob_script="+mobile_script_ei+"&sid="+Math.random();$(document).ready(function(){$.ajax({type:'POST',url:url,dataType:"html",data:{action_id:"s_verify_code"},cache:!1,success:function(newHTML){$('#popup_ei').html(newHTML);$('#overlay_s').css({'display':'block','position':'fixed'});if(editstatus=='Y'){$("#edit_mobile").show('fast');$("#send_code").hide('fast');$("#enter_code").hide('fast');$("#thanks").hide('fast');$("#missed_call").hide('fast')}},xhrFields:{withCredentials:!0}})})}
function checklogin(){var username=document.getElementById("username");var pass=document.getElementById("pass");var reg=/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,14})$/;if(username.value==""){alert("Please enter email");username.focus();return!1}else if(reg.test(chktrim(username.value))==!1){alert("Invalid Email Address.");username.focus();return!1}
if(pass.value==""){alert("Please enter password");pass.focus();return!1}
var action_url=return_member_pop_url('');var url=action_url+"verification_popup_form.php?frmid=checklogin&username="+username.value+"&pass="+pass.value+"&sid="+Math.random();xmlHttp.onreadystatechange=function chklogin(){if(xmlHttp.readyState==4){if(xmlHttp.responseText.length>0){var msg=xmlHttp.responseText;msg=msg.replace(/\s/g,"");document.getElementById("error_login").innerHTML="";var action_url=return_member_pop_url('');if(msg=="Y"){window.location.href=action_url}else{document.getElementById("error_login").style.display='block';document.getElementById("error_login").innerHTML="Incorrect Username / Password"}}}};xmlHttp.open("GET",url,!0);xmlHttp.send(null)}
function sendforgetpassmail(mobile_phone){if(!mobile_phone){var username=document.getElementById("username");if(username.value==""){alert("Please enter email / password.");username.focus();return!1}
var mobile_uername=username.value}else{var mobile_uername=mobile_phone;if(document.domain=='192.168.1.104'){img_path="http://192.168.1.104/static/myfolder-images/loading_01.gif"}else if(document.domain.indexOf('betaei.in')>0){img_path='//ei.exportersindia.com/static/myfolder-images/loading_01.gif'}else{img_path="//static.exportersindia.com/myfolder-images/loading_01.gif"}
var img_dis="<img src='"+img_path+"'>";if(document.getElementById("s2_mobile_phone_id")){document.getElementById('s2_mobile_phone_id').innerHTML=img_dis}}
var action_url=return_member_pop_url('');var url=action_url+"verification_popup_form.php?frmid=sendforgetpasswordmail&username="+mobile_uername+"&sid="+Math.random();xmlHttp.onreadystatechange=function chklogin(){if(xmlHttp.readyState==4){if(xmlHttp.responseText.length>0){var msg=xmlHttp.responseText;var split_msg=msg.split("||");msg=split_msg[0].replace(/\s/g,"");if(document.getElementById('s2_mobile_phone_id')){document.getElementById('s2_mobile_phone_id').innerHTML=""}
if(msg=="Y"){document.getElementById("popup_ei").innerHTML=split_msg[1];$('#overlay_s').css({'display':'block','position':'fixed'})}else if(msg=="F"){document.getElementById("popup_ei").innerHTML=split_msg[1];$('#overlay_s').css({'display':'block','position':'fixed'})}}}};xmlHttp.open("GET",url,!0);xmlHttp.send(null)}
function chktrim(inputString){if(typeof inputString!="string"){return inputString}
var retValue=inputString;var ch=retValue.substring(0,1);while(ch==" "){retValue=retValue.substring(1,retValue.length);ch=retValue.substring(0,1)}
ch=retValue.substring(retValue.length-1,retValue.length);while(ch==" "){retValue=retValue.substring(0,retValue.length-1);ch=retValue.substring(retValue.length-1,retValue.length)}
while(retValue.indexOf("  ")!=-1){retValue=retValue.substring(0,retValue.indexOf("  "))+retValue.substring(retValue.indexOf("  ")+1,retValue.length)}
return retValue}
function requirement_received_popup(action_url){$('#post_req_popup_ei_thanks').load(action_url);$('#overlay_s').css({'display':'block','position':'fixed'})}
function view_product_detail_popup(product_id,member_id,base_url){$.ajax({type:'GET',url:base_url+"/company_product_detail_popup.php",data:{product_id:product_id,member_id:member_id},success:function(responce){$('#post_req_popup_ei').html(responce)},xhrFields:{withCredentials:!0}})}
function BenefitsVerifiedMember(){$('#popup_ei').load('verified-member-benefits.html')}
function emailVerification(mem_baseurl,id,resend){if(resend!='Y'){$("#id_"+id).hide();$("#id_loader").show()}
var url=mem_baseurl+'/popup-verify-email.php';var username=$("#username").val();var new_email=$("#new_email").val();var your_name=encodeURIComponent($("#your_name").val())
$.ajax({type:'POST',url:url,data:{id:id,username:username,new_email:new_email,your_name:your_name,resend:resend},success:function(responce){$("#id_loader").hide();$('#popup_ei').html(responce)},xhrFields:{withCredentials:!0}});$('#overlay_s').css({'display':'block','position':'fixed'})}
function update_email_communication(mem_baseurl,action_do){if(action_do=='change_email_save'){if($('#email_edit_section').is(':visible')==!1){window.location.href=mem_baseurl;return!1}}
var url=mem_baseurl+'/popup-verify-email.php';var username=$("#username").val();var new_email=$("#new_email").val();var your_name=encodeURIComponent($("#your_name").val());var email_reg=/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,14})$/;if(email_reg.test(chktrim(new_email))==!1){$('#id_loader').html('Invalid Email Address.');$("#id_loader").show();$("#new_email").focus();$("#id_change_emailid").hide();return!1}
$("#id_loader").show();$('#id_change_emailid').hide();$.ajax({type:'POST',url:url,data:{username:username,new_email:new_email,your_name:your_name,action_id:action_do},success:function(responce){var split_msg=responce.split("~~");if(split_msg[1].length>0){if(action_do=='change_email_save'){window.location.href=mem_baseurl}else{$('#id_loader').html(split_msg[1]);$('#id_change_emailid').show()}}else{$('#id_loader').html(split_msg[0]);$('#id_change_emailid').hide()}},xhrFields:{withCredentials:!0}})}
function mobileVerifyBuyLeadPurchase(mobile_number,mem_isd_code,inquiry_page_status){var page_id='';if($("#verify_popop_page_id").length>0){page_id=$("#verify_popop_page_id").val()}
var mobile_phone=mobile_number;var action_url=return_member_pop_url('');var mobile_script_ei='N';if($("#mobile_script_ei").length>0){mobile_script_ei='Y'}
var url=action_url+"send_buylead_purchase_otp.php?frmid=send_buylead_purchase_otp&popop_page_id="+page_id+"&mobile_phone="+mobile_phone+"&isd_code="+mem_isd_code+"&mob_script="+mobile_script_ei+"&inq_page_status="+inquiry_page_status+"&sid="+Math.random();var img_path="//static.exportersindia.com/myfolder-images/loading_01.gif";var img_dis="<img src='"+img_path+"'>";if($("#bl_id_loader").length>0){$('#bl_id_loader').html(img_dis)}
$(document).ready(function(){$.ajax({type:'POST',url:url,dataType:"html",data:{action_id:"bl_otp_form"},cache:!1,success:function(newHTML){$('#popup_ei').html(newHTML);$('#bl_id_loader').html("");$('#overlay_s').css({'display':'block','position':'fixed'});setTimeout(function(){$("#message_sent").delay(3000).fadeOut('slow')},1000)},xhrFields:{withCredentials:!0}})})}
$(document).ready(function(){$(document).on("submit","#submit_otp_form",function(e){e.preventDefault();if($("#user_otp").val()==''){alert("Please Enter OTP sent to your mobile and email.");$("#user_otp").focus();return!1}
var page_id='';if($("#verify_popop_page_id").length>0){page_id=$("#verify_popop_page_id").val()}
var action_url=return_member_pop_url('');var mobile_script_ei='N';if($("#mobile_script_ei").length>0){mobile_script_ei='Y'}
var url=action_url+"send_buylead_purchase_otp.php?frmid=verify_buy_lead_otp&popop_page_id="+page_id+"&mob_script="+mobile_script_ei+"&sid="+Math.random();$.ajax({type:'POST',url:url,dataType:"json",data:$('#submit_otp_form').serialize(),cache:!1,success:function(msg){if(msg.status_val=='I'){alert("Invalid OTP");$("#user_otp").focus()}else{alert("OTP Verified.");$('#popup_ei').html("");location.reload()}},xhrFields:{withCredentials:!0}})})});function markAsIrrelevent(lead_id){$.post("irrelevent_popup.php",{lead_id:lead_id},function(data,status){$('#popup_ei').html(data);$('#overlay_s').css({'display':'block','position':'fixed'})})}
function pop_supplier(subject,slno,comp_name,your_name,stt_ct,country,member_id){var action_url=return_member_pop_url('');$.post(action_url+"buyer/place_final_order.php",{slno:slno,comp_name:comp_name,your_name:your_name,stt_ct:stt_ct,country:country,member_id:member_id,subject:subject},function(data,status){$('#popup_ei').html(data);$('#overlay_s').css({'display':'block','position':'fixed'})})}
function place_final_order(slno,member_id,stat){var action_url=return_member_pop_url('');$(function(){$.ajax({url:action_url+"buyer/place_final_order.php",type:"POST",async:!1,data:{update_data:'update_data',slno:slno,member_id:member_id,stat:stat},success:function(getdata_data){var getdata=getdata_data.trim();if(getdata&&getdata=='Y'){alert('Your Order is placed');closeMe()}else{alert('Your Order is cancel');closeMe()}}})})}
function reportIssue(lead_id){$.post("report_issue.php",{lead_id:lead_id},function(data,status){$('#popup_ei').html(data);$('#overlay_s').css({'display':'block','position':'fixed'})})}
function BuyleadContactInfo(redUrl,idd){var action_url=return_member_pop_url('');var url=redUrl+"?"+idd;$(document).ready(function(){$.ajax({type:'POST',url:url,dataType:"html",data:{action_id:"lead_contact_info"},cache:!1,success:function(newHTML){$('#post_req_popup_ei').html(newHTML);$('#overlay_s').css({'display':'block','position':'fixed'})},xhrFields:{withCredentials:!0}})})}
function BuyleadPurchaseInfo(redUrl){var action_url=return_member_pop_url('');var url=redUrl;$(document).ready(function(){$.ajax({type:'POST',url:url,dataType:"html",data:{action_id:"credit_purchase"},cache:!1,success:function(newHTML){$('#post_req_popup_ei').html(newHTML);$('#overlay_s').css({'display':'block','position':'fixed'})},xhrFields:{withCredentials:!0}})})}
function editProfileEmailVerifyMember(action_url,member_id,email,country,verify='N'){var url=action_url+"/verification_popup_form.php";$.ajax({type:'POST',url:url,dataType:"html",data:{action_id:"mobile_email_verify",member_id:member_id,email:email,country:country,url:action_url,verify_mode:verify},cache:!1,success:function(newHTML){$('#popup_ei').html(newHTML);$("#editPrimaryEmail").modal('show');if(verify=='N'){updateVEmailid('N')}
if(verify=='Y'){}},xhrFields:{withCredentials:!0}})}
function updateVEmailid(resend){$('#otp_eeer').html('');var resend_st=resend;var mem_id=$('#emem_id').val();var old_email=$('#eemail').val().trim();if(mem_id&&old_email){var action_url=$('#epath_url').val();var action_url=action_url+'/check_member_mobile.php';$.post(action_url,{action_id:"verify_member_email_data",old_email:old_email,member_id:mem_id},function(data,status){if(status=='success'){var data_arr=data.split("|");if(document.domain=='192.168.1.104'){if(data_arr[1]!=''&&data_arr[1]!=undefined){alert(data_arr[1])}}
if($.trim(data_arr[0])=='email_update_done'&&resend_st=='N'){$("#email_eeer").hide();$('#editEmail').hide();$('#otpStepEmail').show();$('.append_new_email').html(old_email)}else if($.trim(data_arr[0])=='email_update_done'&&resend_st=='Y'){$("#email_eeer").hide();$('#editEmail').hide();$('#resend_code_email').next('span').show()}else{$("#email_eeer").show();$("#email_eeer").html(data_arr[0]);return!1}}})}}
function verify_vemail_otp(){var mem_id=$('#emem_id').val();var old_email=$('#eemail').val().trim();var new_email=$('#new_email').val();var email_inputs=document.getElementsByClassName('email_otp_code'),v_code=[].map.call(email_inputs,function(input){return input.value}).join('');if(v_code.length<4){alert('Enter otp 4 digit long.');$('.email_otp_code').val('');return!1}else if($.isNumeric(v_code)==!1){alert('Invalid otp');$('.email_otp_code').val('');return!1}
var action_url=$('#epath_url').val()+'/check_member_mobile.php';$.post(action_url,{action_id:"verify_vemail_otp",old_email:old_email,member_id:mem_id,email_otp:v_code,new_email:new_email},function(data,status){if(status=='success'){if($.trim(data)=='Done'){$("#email_eeer").hide();$('#email_span_id').hide(old_email);$('#editEmail').hide();$('#otpStepEmail').hide();$('#thanks_mess2').show();var cookieArr=document.cookie.split('; ');var cookieRedirectUrl="";var cookieRes="";for(var i=0;i<cookieArr.length;i++){cookieRes=cookieArr[i].split('=');if(cookieRes[0]=='GO_AFTER_UPDATE_URL'){cookieRedirectUrl=decodeURIComponent(cookieRes[1]);break}}
if(cookieRedirectUrl!=""){window.location.href=cookieRedirectUrl}else{setTimeout(function(){window.location.reload()},3000)}}else if($.trim(data)=='Something Went Wrong Please Try Again !!'){alert(data);$("#email_eeer").hide();$('#email_span_id').hide(old_email);$('#editEmail').hide();$('#otpStepEmail').hide();$('#thanks_mess2').hide();setTimeout(function(){window.location.reload()},1000)}else{alert($.trim(data));$('.email_otp_code').val('');return!1}}})}
function updateEmailid(resend){$('#otp_eeer').html('');var resend_st=resend;var mem_id=$('#emem_id').val();var old_email=$('#eemail').val().trim();var your_email=$('#new_email').val().trim();var action_url=$('#epath_url').val();$('.email_otp_code').val('');if(your_email==''||your_email=='null'){$("#new_email").focus();$("#email_eeer").html('Enter your email.');return!1}else{var regex_email=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i;if(!your_email.match(regex_email)){$("#new_email").focus();$("#email_eeer").html('Enter valid email.');return!1}
$("#email_eeer").hide()}
var action_url=action_url+'/check_member_mobile.php';$.post(action_url,{action_id:"update_request_member_email_data",old_email:old_email,new_email:your_email,member_id:mem_id},function(data,status){if(status=='success'){var data_arr=data.split("|");if(document.domain=='192.168.1.104'){if(data_arr[1]!=''&&data_arr[1]!=undefined){alert(data_arr[1])}}
if($.trim(data_arr[0])=='email_update_done'&&resend_st=='N'){$("#email_eeer").hide();$('#editEmail').hide();$('#otpStepEmail').show();$('.append_new_email').html(your_email)}else if($.trim(data_arr[0])=='email_update_done'&&resend_st=='Y'){$("#email_eeer").hide();$('#editEmail').hide();$('#resend_code_email').next('span').show()}else{$('#otpStepEmail').hide();$('#editEmail').show();$("#email_eeer").show();$("#email_eeer").html(data_arr[0]);return!1}}})}
function verify_email_otp(){$('#otp_eeer').html('');$('#resend_code_msg').hide();var mem_id=$('#emem_id').val();var old_email=$('#eemail').val().trim();var your_email=$('#new_email').val().trim();var email_inputs=document.getElementsByClassName('email_otp_code'),v_code=[].map.call(email_inputs,function(input){return input.value}).join('');if(v_code.length<4){$('#otp_eeer').html('Enter otp 4 digit long');$('.email_otp_code').val('');return!1}else if($.isNumeric(v_code)==!1){$('#otp_eeer').html('Invalid otp');$('.email_otp_code').val('');return!1}
var action_url=$('#epath_url').val()+'/check_member_mobile.php';$.ajax({type:'POST',url:action_url,dataType:"html",data:{action_id:"verify_email_otp",old_email:old_email,new_email:your_email,member_id:mem_id,email_otp:v_code},cache:!1,success:function(data_str){if($.trim(data_str)=='Done'){$('#otp_eeer').html('');$("#email_eeer").hide();$('#email_span_id').hide(your_email);$('#editEmail').hide();$('#otpStepEmail').hide();$('#thanks_mess2').show();var cookieArr=document.cookie.split('; ');var cookieRedirectUrl="";var cookieRes="";for(var i=0;i<cookieArr.length;i++){cookieRes=cookieArr[i].split('=');if(cookieRes[0]=='GO_AFTER_UPDATE_URL'){cookieRedirectUrl=decodeURIComponent(cookieRes[1]);break}}
if(cookieRedirectUrl!=""){window.location.href=cookieRedirectUrl}else{setTimeout(function(){window.location.reload()},10000)}}else if($.trim(data_str)=='Something Went Wrong Please Try Again !!'){alert(data);$("#email_eeer").hide();$('#email_span_id').hide(your_email);$('#editEmail').hide();$('#otpStepEmail').hide();$('#thanks_mess2').hide();setTimeout(function(){window.location.reload()},1000)}else{$('#otp_eeer').html($.trim(data_str));$('.email_otp_code').val('');return!1}},xhrFields:{withCredentials:!0}})}
function verify_email_otp_olddd(){$('#otp_eeer').html('');$('#resend_code_msg').hide();var mem_id=$('#emem_id').val();var old_email=$('#eemail').val().trim();var your_email=$('#new_email').val().trim();var email_inputs=document.getElementsByClassName('email_otp_code'),v_code=[].map.call(email_inputs,function(input){return input.value}).join('');if(v_code.length<4){$('#otp_eeer').html('Enter otp 4 digit long');$('.email_otp_code').val('');return!1}else if($.isNumeric(v_code)==!1){$('#otp_eeer').html('Invalid otp');$('.email_otp_code').val('');return!1}
var action_url=$('#epath_url').val()+'/check_member_mobile.php';$.post(action_url,{action_id:"verify_email_otp",old_email:old_email,new_email:your_email,member_id:mem_id,email_otp:v_code},function(data,status){if(status=='success'){if($.trim(data)=='Done'){$('#otp_eeer').html('');$("#email_eeer").hide();$('#email_span_id').hide(your_email);$('#editEmail').hide();$('#otpStepEmail').hide();$('#thanks_mess2').show();var cookieArr=document.cookie.split('; ');var cookieRedirectUrl="";var cookieRes="";for(var i=0;i<cookieArr.length;i++){cookieRes=cookieArr[i].split('=');if(cookieRes[0]=='GO_AFTER_UPDATE_URL'){cookieRedirectUrl=decodeURIComponent(cookieRes[1]);break}}
if(cookieRedirectUrl!=""){window.location.href=cookieRedirectUrl}else{setTimeout(function(){window.location.reload()},10000)}}else if($.trim(data)=='Something Went Wrong Please Try Again !!'){alert(data);$("#email_eeer").hide();$('#email_span_id').hide(your_email);$('#editEmail').hide();$('#otpStepEmail').hide();$('#thanks_mess2').hide();setTimeout(function(){window.location.reload()},1000)}else{$('#otp_eeer').html($.trim(data));$('.email_otp_code').val('');return!1}}})}
function editClientEmailVerifyMember(action_url,member_id,email,country,verify='N',field){var url=action_url+"/verification_popup_form.php";$.ajax({type:'POST',url:url,dataType:"html",data:{action_id:"client_email_verify",member_id:member_id,email:email,country:country,url:action_url,verify_mode:verify,field:field},cache:!1,success:function(newHTML){$('#popup_ei').html(newHTML);$("#editPrimaryEmail").modal('show');if(verify=='Y'){updateClientEmailid('N')}},xhrFields:{withCredentials:!0}})}
function updateClientEmailid(resend){var resend_st=resend;var mem_id=$('#emem_id').val();var old_email=$('#eemail').val().trim();var your_email=$('#new_email').val().trim();var action_url=$('#epath_url').val();var field=$('#field_email').val();if(your_email==''||your_email=='null'){$("#new_email").focus();return!1}else{var regex_email=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i;if(!your_email.match(regex_email)){$("#new_email").focus();$("#email_eeer").html('Enter valid email.');return!1}
$("#email_eeer").hide()}
var action_url=action_url+'/check_member_mobile.php';$.post(action_url,{action_id:"update_request_client_email_data",old_email:old_email,new_email:your_email,member_id:mem_id,field:field},function(data,status){if(status=='success'){var data_arr=data.split("|");if(document.domain=='192.168.1.104'){if(data_arr[1]!=''&&data_arr[1]!=undefined){alert(data_arr[1])}}
if($.trim(data_arr[0])=='email_update_done'&&resend_st=='N'){$("#email_eeer").hide();$('#editEmail').hide();$('#otpStepEmail').show();$('.append_new_email').html(your_email)}else if($.trim(data_arr[0])=='email_update_done'&&resend_st=='Y'){$("#email_eeer").hide();$('#editEmail').hide();$('#resend_code_email').next('span').show()}else{$("#email_eeer").show();$("#email_eeer").html(data_arr[0]);return!1}}})}
function verify_client_email_otp(){var mem_id=$('#emem_id').val();var old_email=$('#eemail').val().trim();var your_email=$('#new_email').val().trim();var field=$('#field_email').val().trim();var email_inputs=document.getElementsByClassName('email_otp_code'),v_code=[].map.call(email_inputs,function(input){return input.value}).join('');if(v_code.length<6){alert('Enter otp 6 digit long.');$('.email_otp_code').val('');return!1}else if($.isNumeric(v_code)==!1){alert('Invalid otp');$('.email_otp_code').val('');return!1}
var action_url=$('#epath_url').val()+'/check_member_mobile.php';$.post(action_url,{action_id:"verify_client_email_otp",old_email:old_email,new_email:your_email,member_id:mem_id,email_otp:v_code,field:field},function(data,status){if(status=='success'){if($.trim(data)=='Done'){$("#email_eeer").hide();$('#email_span_id').hide(your_email);$('#editEmail').hide();$('#otpStepEmail').hide();$('#thanks_mess2').show();setTimeout(function(){window.location.reload()},10000)}else if($.trim(data)=='Something Went Wrong Please Try Again !!'){alert(data);$("#email_eeer").hide();$('#email_span_id').hide(your_email);$('#editEmail').hide();$('#otpStepEmail').hide();$('#thanks_mess2').hide();setTimeout(function(){window.location.reload()},1000)}else{alert($.trim(data));$('.email_otp_code').val('');return!1}}})}
function mobileVerifyClientMember(redUrl,flag,editstatus,mobile_number,country,field){var redirct=redUrl||'';var tFlag=flag||'';var emailid='';var page_id='';if(document.getElementById("verify_popop_page_id")){page_id=document.getElementById("verify_popop_page_id").value}
var mobile_phone=mobile_number;var mobile_phone_country=country;var country_arr=mobile_phone_country.split("^");var action_url=return_member_pop_url('');var mobile_script_ei='N';if(document.getElementById("mobile_script_ei")){mobile_script_ei='Y'}
var url=action_url+"verification_popup_form.php?frmid=mobile_client_verify&add_edit_mobile="+editstatus+"&popop_page_id="+page_id+"&mobile_phone="+mobile_phone+"&country="+country_arr[0]+"&mob_script="+mobile_script_ei+"&field="+field;$(document).ready(function(){$.ajax({type:'POST',url:url,dataType:"html",data:{action_id:"mobile_verify"},cache:!1,success:function(newHTML){$('#popup_ei').html(newHTML);$('#overlay_s').css({'display':'block','position':'fixed'});if(editstatus=='Y'){$("#edit_mobile").show('fast');$("#send_code").hide('fast');$("#enter_code").hide('fast');$("#thanks").hide('fast');$("#missed_call").hide('fast')}},xhrFields:{withCredentials:!0}})})}
function verify_lead_mob_otp(){var mem_id=$('#lead_member_id').val();var enq_slno=$('#lead_member_id').val().trim();var mob_inputs=document.getElementsByClassName('mob_otp_code'),v_code=[].map.call(mob_inputs,function(input){return input.value}).join('');if(v_code.length==0){alert('Enter otp !!');$('.mob_otp_code').val('');return!1}
if(v_code.length<6){alert('Enter otp 6 digit long.');$('.mob_otp_code').val('');return!1}else if($.isNumeric(v_code)==!1){alert('Invalid otp');$('.mob_otp_code').val('');return!1}
$.post($('#lead_verify_path').val(),{action_id:"verify_lead_mobile_otp",member_id:mem_id,mobile_otp:v_code,enq_slno:enq_slno},function(data,status){if(status=='success'){alert(data)}})}
function editDashbordEmailVerifyMember(action_url,member_id,email,country,verify='N'){var url=action_url+"/verification_popup_form.php";$.ajax({type:'POST',url:url,dataType:"html",data:{action_id:"dashboard_email_verify",member_id:member_id,email:email,country:country,url:action_url,verify_mode:verify},cache:!1,success:function(newHTML){$('#popup_ei').html(newHTML);$("#editPrimaryEmail").modal('show');if(verify=='N'){updateEmailid('N')}
if(verify=='Y'){updateEmailid('N')}},xhrFields:{withCredentials:!0}})}
function AddEmailid(resend){$('#otp_eeer').html('');var resend_st=resend;var mem_id=$('#add_emem_id').val();var old_email=$('#add_eemail').val().trim();var your_email=$('#add_new_email').val().trim();var mem_url=$('#epath_url').val();$('.email_otp_code').val('');if(your_email==''||your_email=='null'){$("#add_new_email").focus();$("#email_eeer").html('Enter your email.');return!1}else{var regex_email=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i;if(!your_email.match(regex_email)){$("#add_new_email").focus();$("#email_eeer").html('Enter valid email.');return!1}
$("#email_eeer").hide()}
var action_url=mem_url+'/check_member_mobile.php';$.post(action_url,{action_id:"update_request_member_email_data",old_email:old_email,new_email:your_email,member_id:mem_id,email_type:"Add"},function(data,status){if(status=='success'){var data_arr=data.split("|");if(document.domain=='192.168.1.104'){if(data_arr[1]!=''&&data_arr[1]!=undefined){alert(data_arr[1])}}
if($.trim(data_arr[0])=='email_update_done'&&resend_st=='N'){editMemEmailVerifyMember(mem_url,mem_id,your_email,country='IN',verify='N','')}else if($.trim(data_arr[0])=='email_update_done'&&resend_st=='Y'){$("#email_eeer").hide();$('#editEmail').hide();$('#resend_code_email').next('span').show()}else{$('#otpStepEmail').hide();$('#editEmail').show();$("#email_eeer").show();$("#email_eeer").html(data_arr[0]);return!1}}})}
function editMemEmailVerifyMember(action_url,member_id,email,country,verify='N',field){$.ajax({type:'POST',url:action_url+"/verification_popup_form.php",dataType:"html",data:{action_id:"mobile_email_verify",member_id:member_id,email:email,country:country,url:action_url,verify_mode:verify,field:field},cache:!1,success:function(newHTML){$('#popup_ei').html(newHTML);$("#editPrimaryEmail").modal('show');$('#editPrimaryEmail .close').hide();$('#otpStepEmail').show();$('#editEmail').hide()},xhrFields:{withCredentials:!0}})}
function editMemMobVerifyMember(action_url,member_id,mobile,country,verify='N',field){$.ajax({type:'POST',url:action_url+"/verification_popup_form.php",dataType:"html",data:{action_id:"member_mobile_verify",member_id:member_id,mobile:mobile,country:country,url:action_url,verify_mode:verify,field:field},cache:!1,success:function(newHTML){$('#popup_ei').html(newHTML);$("#forget_ur_mob_login").modal('show');$('#forget_ur_mob_login .close').hide();$('#otp_opt').show();$('#edit_v_box').hide()},xhrFields:{withCredentials:!0}})}